apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstvaultappapi-deployment
spec:
  selector:
    matchLabels:
      app: firstvaultappapi
  template:
    metadata:
      labels:
        app: firstvaultappapi
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-secret1: k8s/firstvaultapp/testsecrets#secret1
        vault.hashicorp.com/agent-inject-secret-secret2: k8s/firstvaultapp/testsecrets#secret2
        vault.hashicorp.com/role: app
    spec:
      serviceAccountName: vault
      containers:
        - name: firstvaultappapi-container
          image: ghcr.io/arkapravasinha/firstvaultappapi:v0.1.5
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
