apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstvaultappapi-deployment
spec:
  selector:
    matchLabels:
      app: firstvaultappapi
  template:
    metadata:
      labels:
        app: firstvaultappapi
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-inject-secret-secret1.txt: k8s/firstvaultapp/testsecrets
        vault.hashicorp.com/agent-inject-secret-secret2.txt: k8s/firstvaultapp/testsecrets
        vault.hashicorp.com/agent-inject-template-secret1.txt: |
          {{ with secret "k8s/firstvaultapp/testsecrets" }}{{ .Data.data.secret1 }}{{ end }}
        vault.hashicorp.com/agent-inject-template-secret2.txt: |
          {{ with secret "k8s/firstvaultapp/testsecrets" }}{{ .Data.data.secret2 }}{{ end }}
        vault.hashicorp.com/role: firstvaultapp-role
    spec:
      serviceAccountName: firstvaultapp-sa
      containers:
        - name: firstvaultappapi-container
          image: ghcr.io/arkapravasinha/firstvaultappapi:v0.1.12
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
          ports:
            - containerPort: 80
